[package]
name = "risczero_methods"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.0.5", default-features = false, features = ['std'] }
rules = {path = "../../rules"}
operations = {path = "../../operations"}
serde_json = "1.0"
qfilter = "=0.2.1"