[package]
name = "rules"
version = "0.1.0"
edition = "2021"

[dependencies]
qfilter = { version = "0.2.1", features = ['serde'] }
serde = "1.0"
serde_json = "1.0"
serde_bytes = "0.11.15"
serde_yml = "0.0.12"
